---
all:
  vars:
    ansible_user: techstarter
    ansible_ssh_privat_key_file: ./sshkey
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
  children:
    jenkins:
      hosts:
        "jenkins-ts.ddns.net":
          ansible_host: 138.91.50.133
    webserver:
      hosts:
        "webserver.myddns.me":
          ansible_host: 168.61.89.23
